name: Continuous Deployment - Development

on:
  push:
    branches:
      - devel

permissions:
  contents: read

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  Deploy-Resources:
    name: Deploy resources in AWS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - run: cd iac && terraform init -reconfigure -backend-config="envs/devel/devel.tfbackend"
      - run: cd iac && terraform validate && terraform fmt --recursive
      - run: cd iac && terraform plan -var-file="envs/devel/devel.tfvars" -out iac.tfplan
      - run: cd iac && terraform apply -auto-approve iac.tfplan

  Deploy-Application:
    name: Deploy application on S3
    runs-on: ubuntu-latest
    needs: [Deploy-Resources]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 15
      - run: echo "Installing dependencies.." && npm install
      - run: echo "Running buld process..." && npm run build
      - name: Uploading artifacts
        uses: imehedi/actions-awscli-v2@latest
        with:
          args: s3 cp build s3://react-app-devel-fullstacks-2025/ --recursive
